-- AlterTable
ALTER TABLE "AudioFile" ALTER COLUMN "filePath" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "format" SET DATA TYPE VARCHAR(64);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "username" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserAuth" ALTER COLUMN "email" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "password" SET DATA TYPE VARCHAR(255);
